spring:
  application:
    name: Citizen-service
  datasource:
    url: jdbc:mysql://localhost:3306/citizendb
    username: root
    password: root
  jpa:
  properties:
      hibernate:
      ddl-auto: update
